// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	PhoneNumber string             `json:"phone_number"`
	Password    string             `json:"-"`
	Birthdate   pgtype.Date        `json:"birthdate"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
