// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: createUser :execresult
INSERT INTO users (
  name,phone_number,password,birthdate
) VALUES (
  $1,$2,$3,$4
)
`

type createUserParams struct {
	Name        string
	PhoneNumber string
	Password    string
	Birthdate   pgtype.Date
}

func (q *Queries) createUser(ctx context.Context, arg createUserParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createUser,
		arg.Name,
		arg.PhoneNumber,
		arg.Password,
		arg.Birthdate,
	)
}
