// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allUsers = `-- name: AllUsers :many
SELECT id, name, phone_number, password, birthdate, created_at
FROM users
`

func (q *Queries) AllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, allUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.Password,
			&i.Birthdate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name,
                   phone_number,
                   password,
                   birthdate)
VALUES ($1, $2, $3, $4)
RETURNING id, name, phone_number, password, birthdate, created_at
`

type CreateUserParams struct {
	Name        string      `json:"name"`
	PhoneNumber string      `json:"phone_number"`
	Password    string      `json:"-"`
	Birthdate   pgtype.Date `json:"birthdate"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.PhoneNumber,
		arg.Password,
		arg.Birthdate,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
	)
	return i, err
}

const getByPhoneNumber = `-- name: GetByPhoneNumber :one
SELECT id, name, phone_number, password, birthdate, created_at
FROM users
WHERE phone_number = $1
`

func (q *Queries) GetByPhoneNumber(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, phone_number, password, birthdate, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name         = $2,
    birthdate    = $3
where id = $1
RETURNING id, name, phone_number, password, birthdate, created_at
`

type UpdateUserParams struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Birthdate pgtype.Date `json:"birthdate"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Birthdate)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
	)
	return i, err
}
